[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
PeriodicSchurDecompositions = "e5aedecb-f6c0-4c91-b6ff-fbae4296f459"

[compat]
Documenter = "1"
